apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  name: aspcore-multibranch-k8s-ingress
spec:
  rules:
  - host: aspcore-k8s-prod.10.0.2.15.nip.io
    http:
      paths:
      - backend:
          serviceName: aspcore-multibranch-k8s
          servicePort: 80
        path: /
